version: '2'

services:

  simple-print:
    image: camptocamp/mapfish_print:3.23
    environment:
      LOG_LEVEL: INFO
      CATALINA_OPTS: >-
        -Xmx512M
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro
    ports:
      - 8680:8080
